plugins {
    id 'com.android.library'
}

android {
    namespace 'com.kindaras.simpleorm'
    compileSdk = 37

    defaultConfig {
        minSdk = 29
        targetSdk = 37
        versionCode = 4
        versionName = "1.2.1"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    buildFeatures {
        dataBinding = true
    }

    testOptions {
        unitTests {
            includeAndroidResources = true
            returnDefaultValues = true
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.2'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.robolectric:robolectric:4.16.1'
}

afterEvaluate {
    tasks.named("bundleReleaseAar") {
        doLast {
            def file = file("$buildDir/outputs/aar/app-release.aar")
            def newName = "KindarasSimpleOrm-${android.defaultConfig.versionName}.aar"
            file.renameTo(new File(file.parent, newName))
        }
    }
}